# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/radek/Desktop/8051Emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/radek/Desktop/8051Emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/radek/Desktop/8051Emulator/CMakeFiles /home/radek/Desktop/8051Emulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/radek/Desktop/8051Emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named emulator8051

# Build rule for target.
emulator8051: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emulator8051
.PHONY : emulator8051

# fast build rule for target.
emulator8051/fast:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/build
.PHONY : emulator8051/fast

src/Assembler.o: src/Assembler.cpp.o
.PHONY : src/Assembler.o

# target to build an object file
src/Assembler.cpp.o:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/Assembler.cpp.o
.PHONY : src/Assembler.cpp.o

src/Assembler.i: src/Assembler.cpp.i
.PHONY : src/Assembler.i

# target to preprocess a source file
src/Assembler.cpp.i:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/Assembler.cpp.i
.PHONY : src/Assembler.cpp.i

src/Assembler.s: src/Assembler.cpp.s
.PHONY : src/Assembler.s

# target to generate assembly for a file
src/Assembler.cpp.s:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/Assembler.cpp.s
.PHONY : src/Assembler.cpp.s

src/BytesArray.o: src/BytesArray.cpp.o
.PHONY : src/BytesArray.o

# target to build an object file
src/BytesArray.cpp.o:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/BytesArray.cpp.o
.PHONY : src/BytesArray.cpp.o

src/BytesArray.i: src/BytesArray.cpp.i
.PHONY : src/BytesArray.i

# target to preprocess a source file
src/BytesArray.cpp.i:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/BytesArray.cpp.i
.PHONY : src/BytesArray.cpp.i

src/BytesArray.s: src/BytesArray.cpp.s
.PHONY : src/BytesArray.s

# target to generate assembly for a file
src/BytesArray.cpp.s:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/BytesArray.cpp.s
.PHONY : src/BytesArray.cpp.s

src/Processor.o: src/Processor.cpp.o
.PHONY : src/Processor.o

# target to build an object file
src/Processor.cpp.o:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/Processor.cpp.o
.PHONY : src/Processor.cpp.o

src/Processor.i: src/Processor.cpp.i
.PHONY : src/Processor.i

# target to preprocess a source file
src/Processor.cpp.i:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/Processor.cpp.i
.PHONY : src/Processor.cpp.i

src/Processor.s: src/Processor.cpp.s
.PHONY : src/Processor.s

# target to generate assembly for a file
src/Processor.cpp.s:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/Processor.cpp.s
.PHONY : src/Processor.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/emulator8051.dir/build.make CMakeFiles/emulator8051.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... emulator8051"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... src/Assembler.o"
	@echo "... src/Assembler.i"
	@echo "... src/Assembler.s"
	@echo "... src/BytesArray.o"
	@echo "... src/BytesArray.i"
	@echo "... src/BytesArray.s"
	@echo "... src/Processor.o"
	@echo "... src/Processor.i"
	@echo "... src/Processor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

